### ISSUE TITLE
[TASK]: Update login button

### ISSUE THREAD

**Issue by Jo9871** [webdevcody/code-racer#111]
### Task Summary

- [x] Make login button login directly with GitHub instead of redirecting to a login page first
- [x] Update button style to look neater
- [x] Add GitHub Logo to indicate it will log in with GitHub

### Acceptance criteria

- [x] One click login with GitHub
- [x] Neater button style
- [x] GitHub logo
