### ISSUE TITLE
[TASK]: Setup project level auto-format with prettier

### ISSUE THREAD

**Issue by shardel23** [webdevcody/code-racer#115]
### Task Summary

Currently, there's no project config for formatting.
Since there are multiple contributors, each with their individual prettier config, many files are formatted differently.
This is already bad, but the real pain is that in each commit, touched files are being formatted again and again differently, leading to big and messy commits.

We should add some project config for formatting, which will ensure that each contributor working with prettier will use the same formatting rules as everyone.
We should also take into account contributors who don't have prettier vscode extension installed, and should force the code to be formatted all the same.

I suggest to do the following:
- [ ] Add prettier as a dev dependency
- [ ] Create formatting config file for prettier (.prettierrc file)
- [ ] Populate the .prettierrc with accepted rules (This is the part I'm not sure about what rules exactly to use - Perhaps Cody can decide?)
- [ ] Run a one-time format script for all files to ensure all files are synced with the new formatting rules
- [ ] Create format pre-commit hook to be run on every commit

A guide on how to configure prettier: https://khalilstemmler.com/blogs/tooling/prettier/

Would love to get endorsement for this issue since this can be a cross-project change which will make changes in all files.

### Acceptance criteria

- [ ] All files have the same formatting
- [ ] All future commits will be auto-formatted by the same formatting rules.

**Comment by webdevcody** [comment]
seems reasonable to me, just use the defaults of prettier.

**Comment by andyphl** [comment]
Maybe also add prettier-plugin-tailwindcss for tailwindcss classes sorting?

**Comment by mshubitidze** [comment]
> seems reasonable to me, just use the defaults of prettier.

i can set this up
